server:
  port: ${PORT:8082}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_xgz8uSxKQ

aws:
  cognito:
    client-id: 2ju9qhemekdnqg14c7m5r9ge3p