server:
  port: ${PORT:8081}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:orders}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_xgTBxHxEQ

aws:
  cognito:
    client-id: 2juwqhwmo4dncg14c3nsr4gx4p